services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Let's Encrypt configuration
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=email@framedle.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - web
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  app:
    image: ghcr.io/kadeem-lewis/framedle:${GIT_COMMIT_HASH:-latest}
    networks:
      - web
    secrets:
      - doppler_token
    environment:
      - DOPPLER_TOKEN_FILE=/run/secrets/doppler_token
    entrypoint: > # make secrets available to the app
      sh -c 'export DOPPLER_TOKEN="$$(cat $$DOPPLER_TOKEN_FILE)"
      && exec doppler run -- node --import ./.output/server/sentry.server.config.mjs ./.output/server/index.mjs'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1 # Update one instance at a time
        delay: 10s
        order: start-first
        failure_action: rollback
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.framedle-staging.rule=Host(`staging.framedle.com`)"
      - "traefik.http.routers.framedle-staging.entrypoints=websecure"
      - "traefik.http.routers.framedle-staging.tls.certresolver=myresolver"
      - "traefik.http.services.framedle-staging.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  app-prod:
    image: ghcr.io/kadeem-lewis/framedle:64066570633c6b19818792edc0ed03084e4be40f
    networks:
      - web
    secrets:
      - database_url
      - sentry_auth_token
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - SENTRY_AUTH_TOKEN_FILE=/run/secrets/sentry_auth_token
      - NUXT_PUBLIC_SCRIPTS_UMAMI_ANALYTICS_WEBSITE_ID=28866016-a151-4d95-bc2e-c31779a8aaad
      - NUXT_PUBLIC_SCRIPTS_UMAMI_ANALYTICS_SCRIPT_INPUT_SRC=https://analytics.kadeemlewis.com/script.js
    entrypoint: > # make secrets available to the app
      sh -c 'export NUXT_DATABASE_URL="$$(cat $$DATABASE_URL_FILE)"
      && export SENTRY_AUTH_TOKEN="$$(cat $$SENTRY_AUTH_TOKEN_FILE)"
      && exec node --import ./.output/server/sentry.server.config.mjs ./.output/server/index.mjs'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1 # Update one instance at a time
        delay: 10s
        order: start-first
        failure_action: rollback
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.framedle.rule=Host(`framedle.com`) || Host(`www.framedle.com`)"
      - "traefik.http.routers.framedle.entrypoints=websecure"
      - "traefik.http.routers.framedle.tls.certresolver=myresolver"
      - "traefik.http.services.framedle.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: redis:8.4-alpine
    volumes:
      - redis-data:/data
    networks:
      - web
    secrets:
      - redis_password
    command: >
      sh -c 'redis-server --save 60 1 --loglevel warning --databases 2 --appendonly yes --requirepass \"$(cat /run/secrets/redis_password)\"'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  letsencrypt:
  redis-data:
networks:
  web:
    driver: overlay
secrets:
  database_url:
    external: true
  sentry_auth_token:
    external: true
  doppler_token:
    external: true
  redis_password:
    external: true
