export const progenitors: { [key: string]: string } = {
  Baruuk: "Impact",
  "Baruuk Prime": "Impact",
  Dante: "Impact",
  Gauss: "Impact",
  "Gauss Prime": "Impact",
  Grendel: "Impact",
  "Grendel Prime": "Impact",
  Rhino: "Impact",
  "Rhino Prime": "Impact",
  Sevagoth: "Impact",
  "Sevagoth Prime": "Impact",
  Wukong: "Impact",
  "Wukong Prime": "Impact",
  Zephyr: "Impact",
  "Zephyr Prime": "Impact",
  Chroma: "Heat",
  "Chroma Prime": "Heat",
  Ember: "Heat",
  "Ember Prime": "Heat",
  Inaros: "Heat",
  "Inaros Prime": "Heat",
  Jade: "Heat",
  Koumei: "Heat",
  Kullervo: "Heat",
  Nezha: "Heat",
  "Nezha Prime": "Heat",
  Protea: "Heat",
  "Protea Prime": "Heat",
  Vauban: "Heat",
  "Vauban Prime": "Heat",
  Wisp: "Heat",
  "Wisp Prime": "Heat",
  Frost: "Cold",
  "Frost Prime": "Cold",
  Gara: "Cold",
  "Gara Prime": "Cold",
  Hildryn: "Cold",
  "Hildryn Prime": "Cold",
  Revenant: "Cold",
  "Revenant Prime": "Cold",
  Styanax: "Cold",
  Titania: "Cold",
  "Titania Prime": "Cold",
  Trinity: "Cold",
  "Trinity Prime": "Cold",
  Banshee: "Electricity",
  "Banshee Prime": "Electricity",
  Caliban: "Electricity",
  Excalibur: "Electricity",
  "Excalibur Prime": "Electricity",
  "Excalibur Umbra": "Electricity",
  Gyre: "Electricity",
  Limbo: "Electricity",
  "Limbo Prime": "Electricity",
  Nova: "Electricity",
  "Nova Prime": "Electricity",
  Valkyr: "Electricity",
  "Valkyr Prime": "Electricity",
  Volt: "Electricity",
  "Volt Prime": "Electricity",
  Atlas: "Toxin",
  "Atlas Prime": "Toxin",
  Dagath: "Toxin",
  Ivara: "Toxin",
  "Ivara Prime": "Toxin",
  Khora: "Toxin",
  "Khora Prime": "Toxin",
  Nekros: "Toxin",
  "Nekros Prime": "Toxin",
  Nidus: "Toxin",
  "Nidus Prime": "Toxin",
  Oberon: "Toxin",
  "Oberon Prime": "Toxin",
  Saryn: "Toxin",
  "Saryn Prime": "Toxin",
  Citrine: "Magnetic",
  Harrow: "Magnetic",
  "Harrow Prime": "Magnetic",
  Hydroid: "Magnetic",
  "Hydroid Prime": "Magnetic",
  Lavos: "Magnetic",
  Mag: "Magnetic",
  "Mag Prime": "Magnetic",
  Mesa: "Magnetic",
  "Mesa Prime": "Magnetic",
  Xaku: "Magnetic",
  Yareli: "Magnetic",
  Ash: "Radiation",
  "Ash Prime": "Radiation",
  Equinox: "Radiation",
  "Equinox Prime": "Radiation",
  Garuda: "Radiation",
  "Garuda Prime": "Radiation",
  Loki: "Radiation",
  "Loki Prime": "Radiation",
  Mirage: "Radiation",
  "Mirage Prime": "Radiation",
  Nyx: "Radiation",
  "Nyx Prime": "Radiation",
  Octavia: "Radiation",
  "Octavia Prime": "Radiation",
  Qorvex: "Radiation",
  Voruna: "Radiation",
};
